apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv1-volume
  labels:
    type: local
spec:
  storageClassName: manual1
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv1-claim
spec:
  storageClassName: manual1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

