// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1685006717);
user_pref("browser.search.region", "GR");
user_pref("calendar.caldav.googleResync", 1685006715);
user_pref("calendar.list.sortOrder", "266c1467-2b13-4b56-b998-72a78a987d43");
user_pref("calendar.registry.266c1467-2b13-4b56-b998-72a78a987d43.calendar-main-default", true);
user_pref("calendar.registry.266c1467-2b13-4b56-b998-72a78a987d43.calendar-main-in-composite", true);
user_pref("calendar.registry.266c1467-2b13-4b56-b998-72a78a987d43.disabled", true);
user_pref("calendar.registry.266c1467-2b13-4b56-b998-72a78a987d43.name", "Home");
user_pref("calendar.registry.266c1467-2b13-4b56-b998-72a78a987d43.type", "storage");
user_pref("calendar.registry.266c1467-2b13-4b56-b998-72a78a987d43.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Europe/Bucharest");
user_pref("calendar.ui.version", 3);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1685006712);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230407145224");
user_pref("extensions.lastAppVersion", "102.10.0");
user_pref("extensions.lastPlatformVersion", "102.10.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"2a14e9a2-407a-48ea-80b9-0565158797e5\",\"google@search.mozilla.org\":\"cacdc2b2-368d-460e-a2fc-1736b5e897f8\",\"ddg@search.mozilla.org\":\"fe1c5798-fd5f-4473-b0c2-e13e2cffd70a\",\"amazon@search.mozilla.org\":\"13350863-771b-4149-bd77-adbdf4641d92\",\"chambers-en-GB@search.mozilla.org\":\"aa5e5c1f-c992-4c51-a833-807703798e89\",\"wikipedia@search.mozilla.org\":\"755ea5a4-0ef1-4b44-81c0-5c4a815c262f\",\"bing@search.mozilla.org\":\"527b5636-b0f8-4e9d-acf8-10d5ea5463bc\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 34);
user_pref("mailnews.database.global.datastore.id", "01fb8d73-ab86-4bb1-961e-7ef53834d29");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "102.10.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("toolkit.telemetry.cachedClientID", "fe683efa-a3e6-4dfe-87ad-785ad27f4723");
user_pref("toolkit.telemetry.previousBuildID", "20230407145224");
